/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mob;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.*;
import oracle.jdbc.pool.*;
import oracle.sql.*;

/**
 *
 * @author NADA
 */
public class Branch extends javax.swing.JFrame {

    Employee e=new Employee();
     Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    DefaultTableModel model=new DefaultTableModel();
   
    /**
     * Creates new form Gallery
     */
    public Branch() {
        initComponents();
        setLocationRelativeTo(null);
        Object cul[]={"Id","Name","City","Street","Phone_num"};
        model.setColumnIdentifiers(cul);
        jTable1.setModel(model);
         
        
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextid = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jTextcity = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextstreet = new javax.swing.JTextField();
        jTextnum = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextsearch = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        Update = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setBackground(new java.awt.Color(153, 153, 255));
        jTable1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Id", "Name", "City", "Street", "Phone_num"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jTable1.addInputMethodListener(new java.awt.event.InputMethodListener() {
            public void caretPositionChanged(java.awt.event.InputMethodEvent evt) {
            }
            public void inputMethodTextChanged(java.awt.event.InputMethodEvent evt) {
                jTable1InputMethodTextChanged(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 970, 230));
        jPanel1.add(jTextid, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 110, 85, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("ID");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Name");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 90, 40, -1));
        jPanel1.add(jTextname, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 110, 105, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("City");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 210, -1, -1));
        jPanel1.add(jTextcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 230, 96, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Street");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Phone_num");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, -1, -1));
        jPanel1.add(jTextstreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 230, 147, -1));
        jPanel1.add(jTextnum, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 180, 120, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon("C:\\Users\\NADA\\Documents\\NetBeansProjects\\mob\\src\\main\\java\\com\\mycompany\\mob\\image\\building.png")); // NOI18N
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 110, 200, 190));

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(51, 51, 255));
        jButton4.setText("Back");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, 70, -1));

        jPanel2.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 36)); // NOI18N
        jLabel1.setText("Branch");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(390, 390, 390)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(441, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 80));

        jPanel3.setBackground(new java.awt.Color(204, 204, 204));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Searsh");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ID", "name", "City", "Street", "phone_num" }));

        jLabel8.setIcon(new javax.swing.ImageIcon("C:\\Users\\NADA\\Documents\\NetBeansProjects\\mob\\src\\main\\java\\com\\mycompany\\mob\\image\\search.png")); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)
                .addComponent(jTextsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2)
                        .addGap(44, 44, 44))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(17, 17, 17))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 250, 160));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("add new branch");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 270, -1, -1));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setText(" Delete branch");
        jButton3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 580, -1, -1));

        Update.setBackground(new java.awt.Color(153, 153, 255));
        Update.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        Update.setForeground(new java.awt.Color(51, 102, 255));
        Update.setText("Update");
        Update.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        Update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateActionPerformed(evt);
            }
        });
        jPanel1.add(Update, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 300, 80, -1));

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 102, 255));
        jButton5.setText("Show");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 270, 100, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 620, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

  
 public void updatetable(){
     
     
         String sql="SELECT Id,Name,City,Street,Phone_num from Branch";
         try{
              DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
              String url="jdbc:oracle:thin:@localhost:1522:orcl";
              con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
            Object[] columnData=new Object[5];
             
             while(rs.next()){
               columnData[0]=rs.getInt("Id");
               columnData[1]=rs.getString("Name");
               columnData[2]=rs.getString("City");
               columnData[3]=rs.getString("Street");
               columnData[4]=rs.getString("phone_num");
               model.addRow(columnData);
             }
          
         }
        catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
        
     } 
     }
 
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
         setVisible(false);
        
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        add_branch b=new add_branch();
        b.setVisible(true);
        b.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        jTextid.setText("");
        jTextname.setText("");
            jTextcity.setText("");
            jTextstreet.setText("");
       jTextnum.setText("");
        DefaultTableModel imodel=(DefaultTableModel) jTable1.getModel();
         if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                 JOptionPane.showMessageDialog(null, "No data to deleted",
                         "Delete Customer",JOptionPane.OK_OPTION);
            }
            else{
                JOptionPane.showMessageDialog(null, "Select a row to delete ",
                        "Delete Customer",JOptionPane.OK_OPTION);
            }
        }
         else{
             try{
                 
             DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             int i=jTable1.getSelectedRow();
             int s=Integer.parseInt(jTable1.getValueAt(i, 0).toString());
             String sql="Delete from Branch where ID='"+s+"'";
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             
             /*while(rs.next()){
                 if(String.valueOf(rs.getInt("ID")).equals(model.getValueAt(i, 0))){
                     rs.deleteRow();
                 }
             }*/
             imodel.removeRow(jTable1.getSelectedRow());
             pst.executeUpdate();
            rs.close();
            pst.close();
             }
             catch(Exception e){
                 JOptionPane.showMessageDialog(null,e);
             }
         }
         
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod=(DefaultTableModel) jTable1.getModel();
         mod.setRowCount(0);
        int s=jComboBox1.getSelectedIndex();
      
        if(s==0){
       
        try{
            int i=Integer.parseInt(jTextsearch.getText());
            String sql="Select Id,name,city,street,phone_num from Branch where id='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object o[]=new Object[5];
             while(rs.next()){
             o[0]=rs.getInt(1);
             o[1]=rs.getString(2);
             o[2]=rs.getString(3);
             o[3]=rs.getString(4);
             o[4]=rs.getString(5);
             mod.addRow(o);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }          
        else if(s==1){
    
        try{
            String i=jTextsearch.getText();
            String sql="Select Id,name,city,street,phone_num from Branch where name='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object o[]=new Object[5];
             while(rs.next()){
             o[0]=rs.getInt(1);
             o[1]=rs.getString(2);
             o[2]=rs.getString(3);
             o[3]=rs.getString(4);
             o[4]=rs.getString(5);
             mod.addRow(o);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }          
        else if(s==2){
        
        try{
            String i=jTextsearch.getText();
            String sql="Select Id,name,city,street,phone_num from Branch where city='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object o[]=new Object[5];
             while(rs.next()){
             o[0]=rs.getInt(1);
             o[1]=rs.getString(2);
             o[2]=rs.getString(3);
             o[3]=rs.getString(4);
             o[4]=rs.getString(5);
             mod.addRow(o);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }         
        else if(s==3){
        mod.setRowCount(0);
        try{
            String i=jTextsearch.getText();
            String sql="Select Id,name,city,street,phone_num from Branch where street='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object o[]=new Object[5];
             while(rs.next()){
             o[0]=rs.getInt(1);
             o[1]=rs.getString(2);
             o[2]=rs.getString(3);
             o[3]=rs.getString(4);
             o[4]=rs.getString(5);
             mod.addRow(o);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }    
        else{
        mod.setRowCount(0);
        try{
            String i=jTextsearch.getText();
            String sql="Select Id,name,city,street,phone_num from Branch where phone_num='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object o[]=new Object[5];
             while(rs.next()){
             o[0]=rs.getInt(1);
             o[1]=rs.getString(2);
             o[2]=rs.getString(3);
             o[3]=rs.getString(4);
             o[4]=rs.getString(5);
             mod.addRow(o);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }          
    }//GEN-LAST:event_jButton2ActionPerformed

    private void UpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod=(DefaultTableModel) jTable1.getModel();
       
           int row= jTable1.getSelectedRow();
            
        try{
             DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
            int value=Integer.parseInt(mod.getValueAt(row, 0).toString());
            String sql="Update Branch set name=?,city=?,street=?,phone_num=? where id='"+value+"'";
            pst=con.prepareStatement(sql);
            pst.setString(1, jTextname.getText());
            pst.setString(2, jTextcity.getText());
            pst.setString(3, jTextstreet.getText());
            pst.setString(4, jTextnum.getText());
             
            pst.executeUpdate();
            pst.close();
            
            JOptionPane.showMessageDialog(null, "update sccesfull");
        }
        catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        jTextid.setText("");
        jTextname.setText("");
            jTextcity.setText("");
            jTextstreet.setText("");
       jTextnum.setText("");
             
        mod.setRowCount(0);
        updatetable();
            
             
       
       
    }//GEN-LAST:event_UpdateActionPerformed

    private void jTable1InputMethodTextChanged(java.awt.event.InputMethodEvent evt) {//GEN-FIRST:event_jTable1InputMethodTextChanged
       
        
        
    }//GEN-LAST:event_jTable1InputMethodTextChanged

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod=(DefaultTableModel) jTable1.getModel();
        mod.setRowCount(0);
        updatetable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
        jTextid.setText(jTable1.getValueAt(row, 0).toString());
        jTextname.setText(jTable1.getValueAt(row, 1).toString());
        jTextcity.setText(jTable1.getValueAt(row, 2).toString());
        jTextstreet.setText(jTable1.getValueAt(row, 3).toString());
        jTextnum.setText(jTable1.getValueAt(row, 4).toString());
    }//GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Branch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Branch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Branch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Branch.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Branch().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Update;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextcity;
    public static javax.swing.JTextField jTextid;
    private javax.swing.JTextField jTextname;
    private javax.swing.JTextField jTextnum;
    private javax.swing.JTextField jTextsearch;
    private javax.swing.JTextField jTextstreet;
    // End of variables declaration//GEN-END:variables
}
