/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.mob;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import oracle.jdbc.*;
import oracle.jdbc.pool.*;
import oracle.sql.*;

/**
 *
 * @author NADA
 */
public class Employee extends javax.swing.JFrame {

    Connection con=null;
    PreparedStatement pst=null;
    ResultSet rs=null;
    DefaultTableModel model=new DefaultTableModel();
    /**
     * Creates new form Employee
     */
    public Employee() {
        initComponents();
        setLocationRelativeTo(null);
        Object cul[]={"SSN","FName","Minit","LName","City","Street","Six","Salary","job_type","Hour","branch_id","insurance_id"};
        model.setColumnIdentifiers(cul);
        jTable1.setModel(model);
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jTextssn = new javax.swing.JTextField();
        jTextname = new javax.swing.JTextField();
        jTextminit = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jTextcity = new javax.swing.JTextField();
        jTextstreet = new javax.swing.JTextField();
        jTextsalary = new javax.swing.JTextField();
        jTextjob = new javax.swing.JTextField();
        jCheckF = new javax.swing.JCheckBox();
        jCheckM = new javax.swing.JCheckBox();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTexthour = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton3 = new javax.swing.JButton();
        jTextbid = new javax.swing.JTextField();
        jTextiid = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jTextsearch = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextlname = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Matura MT Script Capitals", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Employee");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(369, 369, 369)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(432, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(35, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 90));

        jLabel2.setIcon(new javax.swing.ImageIcon("C:\\Users\\NADA\\Documents\\NetBeansProjects\\mob\\src\\main\\java\\com\\mycompany\\mob\\image\\employee.png")); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 10, 300, 280));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("SSN");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("FName");
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 120, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Minit");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("LName");
        jPanel2.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 120, -1, -1));
        jPanel2.add(jTextssn, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 140, 100, -1));
        jPanel2.add(jTextname, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 140, 100, -1));
        jPanel2.add(jTextminit, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 140, 90, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("City");
        jPanel2.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Street");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, -1, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel9.setText("Sex");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 170, -1, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel10.setText("Salary");
        jPanel2.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 170, -1, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel11.setText("job_type");
        jPanel2.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 170, -1, -1));
        jPanel2.add(jTextcity, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 260, 100, -1));
        jPanel2.add(jTextstreet, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 200, 80, -1));
        jPanel2.add(jTextsalary, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 190, 80, -1));
        jPanel2.add(jTextjob, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 190, 130, -1));

        jCheckF.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckF.setText("FMale");
        jPanel2.add(jCheckF, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 190, -1, -1));

        jCheckM.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jCheckM.setText("Male");
        jPanel2.add(jCheckM, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 210, -1, -1));

        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel13.setText("Hour");
        jPanel2.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 240, -1, -1));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel14.setText("branchid");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, -1, -1));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel15.setText("Insurance_id");
        jPanel2.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, -1, -1));

        jTexthour.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTexthourActionPerformed(evt);
            }
        });
        jPanel2.add(jTexthour, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 260, 80, -1));

        jTable1.setBackground(new java.awt.Color(153, 153, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "SSN", "FName", "Minit", "LName", "City", "Steet", "Sex", "Salary", "job_type", "Hour", "bransh_id", "insurance_id"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 340, 970, 230));

        jButton3.setBackground(new java.awt.Color(153, 153, 255));
        jButton3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 51, 255));
        jButton3.setText("Back");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 580, -1, -1));
        jPanel2.add(jTextbid, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 260, 80, -1));
        jPanel2.add(jTextiid, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 90, -1));

        jPanel4.setBackground(new java.awt.Color(204, 204, 204));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jButton2.setBackground(new java.awt.Color(153, 153, 255));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton2.setForeground(new java.awt.Color(51, 51, 255));
        jButton2.setText("Search");
        jButton2.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SSN", "Fname", "Mname", "Lname", "City", "Street", "Six", "Salary", "job_tpe", "hour", "branch_id", "insurance_id" }));
        jComboBox1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\NADA\\Documents\\NetBeansProjects\\mob\\src\\main\\java\\com\\mycompany\\mob\\image\\search.png")); // NOI18N

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel12))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton2)
                        .addGap(17, 17, 17)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextsearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18))
        );

        jPanel2.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 100, 230, 150));

        jButton4.setBackground(new java.awt.Color(153, 153, 255));
        jButton4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton4.setForeground(new java.awt.Color(0, 51, 255));
        jButton4.setText("Delete employee");
        jButton4.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 580, 113, -1));

        jButton6.setBackground(new java.awt.Color(153, 153, 255));
        jButton6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton6.setForeground(new java.awt.Color(51, 102, 255));
        jButton6.setText("Show");
        jButton6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 70, -1));

        jButton1.setBackground(new java.awt.Color(153, 153, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 51, 255));
        jButton1.setText("Add new employee");
        jButton1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 260, -1, -1));

        jButton5.setBackground(new java.awt.Color(153, 153, 255));
        jButton5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jButton5.setForeground(new java.awt.Color(51, 51, 255));
        jButton5.setText("Update");
        jButton5.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 260, 62, -1));
        jPanel2.add(jTextlname, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 140, 100, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 970, 620));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        jTextssn.setText("");
            jTextname.setText("");
            jTextminit.setText("");
            jTextlname.setText("");
            jTextcity.setText("");
            jTextstreet.setText("");
            jCheckF.setSelected(false);
            jCheckM.setSelected(false);
            jTextsalary.setText("");
            jTextjob.setText("");
            jTexthour.setText("");
            jTextbid.setText("");
            jTextiid.setText("");
        DefaultTableModel imodel=(DefaultTableModel) jTable1.getModel();
        if(jTable1.getSelectedRow()==-1){
            if(jTable1.getRowCount()==0){
                JOptionPane.showMessageDialog(null, "No data to deleted",
                    "Delete Employee",JOptionPane.OK_OPTION);
            }
            else{
                JOptionPane.showMessageDialog(null, "Select a row to delete ",
                    "Delete Employee",JOptionPane.OK_OPTION);
            }
        }
        else{
            try{

                DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
                String url="jdbc:oracle:thin:@localhost:1522:orcl";
                con=DriverManager.getConnection(url,"mob","mob");
                int i=jTable1.getSelectedRow();
                String s=jTable1.getValueAt(i, 0).toString();
                String sql="Delete from Employee where SSN='"+s+"'";
                pst=con.prepareStatement(sql);
                rs=pst.executeQuery();
                imodel.removeRow(jTable1.getSelectedRow());
                pst.executeUpdate();
                rs.close();
                pst.close();
            }
            catch(Exception e){
                JOptionPane.showMessageDialog(null,e);
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        setVisible(false);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
       
        addEmployee e=new addEmployee();
        e.setVisible(true);
        e.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTexthourActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTexthourActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTexthourActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod=(DefaultTableModel) jTable1.getModel();
         mod.setRowCount(0);
        int s=jComboBox1.getSelectedIndex();
      
        if(s==0){
        try{
            String i=jTextsearch.getText();
            String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee where ssn='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object columnData[]=new Object[12];
             while(rs.next()){
             columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
             mod.addRow(columnData);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }          
        else if(s==1){
        try{
            String i=jTextsearch.getText();
            String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee where fname='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object columnData[]=new Object[12];
             while(rs.next()){
             columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
             mod.addRow(columnData);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }     
        else if(s==2){
        try{
            String i=jTextsearch.getText();
            String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee where minit='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object columnData[]=new Object[12];
             while(rs.next()){
             columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
             mod.addRow(columnData);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }     
        else if(s==3){
        try{
            String i=jTextsearch.getText();
            String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee where lname='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object columnData[]=new Object[12];
             while(rs.next()){
             columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
             mod.addRow(columnData);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }     
          else if(s==4){
        try{
            String i=jTextsearch.getText();
            String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee where city='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object columnData[]=new Object[12];
             while(rs.next()){
             columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
             mod.addRow(columnData);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }  
        else if(s==5){
        try{
            String i=jTextsearch.getText();
            String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee where street='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object columnData[]=new Object[12];
             while(rs.next()){
             columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
             mod.addRow(columnData);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }    
        else if(s==6){
        try{
            String i=jTextsearch.getText();
            String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee where six='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object columnData[]=new Object[12];
             while(rs.next()){
             columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
             mod.addRow(columnData);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }     
        else if(s==7){
        try{
            Float i=Float.parseFloat(jTextsearch.getText());
            String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee where salary='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object columnData[]=new Object[12];
             while(rs.next()){
             columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
             mod.addRow(columnData);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }   
        else if(s==8){
        try{
            String i=jTextsearch.getText();
            String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee where jobtype='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object columnData[]=new Object[12];
             while(rs.next()){
             columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
             mod.addRow(columnData);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }     
        else if(s==9){
        try{
            int i=Integer.parseInt(jTextsearch.getText());
            String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee where hour='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object columnData[]=new Object[12];
             while(rs.next()){
             columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
             mod.addRow(columnData);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }   
        else if(s==10){
        try{
            int i=Integer.parseInt(jTextsearch.getText());
            String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee where fid='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object columnData[]=new Object[12];
             while(rs.next()){
             columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
             mod.addRow(columnData);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }     
        else {
        try{
            int i=Integer.parseInt(jTextsearch.getText());
            String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee where IID='"+i+"'";
            DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object columnData[]=new Object[12];
             while(rs.next()){
             columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
             mod.addRow(columnData);
        }
             jTextsearch.setText("");
             pst.close();
             rs.close();
        }
      catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        }     
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod=(DefaultTableModel) jTable1.getModel();
        mod.setRowCount(0);
        updatetable();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel mod=(DefaultTableModel) jTable1.getModel();
       
           int row= jTable1.getSelectedRow();
            
        try{
             DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
            String value=mod.getValueAt(row, 0).toString();
            String sql="Update Employee set FName=?,Minit=?,LName=?,City=?,Street=?,Six=?,Salary=?,jobtype=?,Hour=?,FID=?,IId=? where ssn='"+value+"'";
            pst=con.prepareStatement(sql);
            
            pst.setString(1, jTextname.getText());
            pst.setString(2, jTextminit.getText());
            pst.setString(3, jTextlname.getText());
            pst.setString(4, jTextcity.getText());
            pst.setString(5, jTextstreet.getText());
            if(jCheckF.isSelected()){ pst.setString(6, "F"); }
            else{pst.setString(6, "M");}
            pst.setFloat(7,Float.parseFloat(jTextsalary.getText()));
            pst.setString(8, jTextjob.getText());
            pst.setInt(9, Integer.parseInt(jTexthour.getText()));
            pst.setInt(10, Integer.parseInt(jTextbid.getText()));
            pst.setInt(11, Integer.parseInt(jTextiid.getText()));
            
             
            pst.executeUpdate();
            pst.close();
            
            JOptionPane.showMessageDialog(null, "update sccesfull");
        }
        catch(HeadlessException|SQLException e){
         JOptionPane.showMessageDialog(null, e);
     }
        
        jTextssn.setText("");
            jTextname.setText("");
            jTextminit.setText("");
            jTextlname.setText("");
            jTextcity.setText("");
            jTextstreet.setText("");
            jCheckF.setSelected(false);
            jCheckM.setSelected(false);
            jTextsalary.setText("");
            jTextjob.setText("");
            jTexthour.setText("");
            jTextbid.setText("");
            jTextiid.setText("");
        
        
        mod.setRowCount(0);
        updatetable();
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        int row=jTable1.getSelectedRow();
            jTextssn.setText(jTable1.getValueAt(row, 0).toString());
            jTextname.setText(jTable1.getValueAt(row, 1).toString());
            jTextminit.setText(jTable1.getValueAt(row, 2).toString());
            jTextlname.setText(jTable1.getValueAt(row, 3).toString());
            jTextcity.setText(jTable1.getValueAt(row, 4).toString());
            jTextstreet.setText(jTable1.getValueAt(row, 5).toString());
           if(jTable1.getValueAt(row, 6).toString().equals("F"))
               jCheckF.setSelected(true);
           else jCheckM.setSelected(true);
            jTextsalary.setText(jTable1.getValueAt(row, 7).toString());
            jTextjob.setText(jTable1.getValueAt(row, 8).toString());
            jTexthour.setText(jTable1.getValueAt(row, 9).toString());
            jTextbid.setText(jTable1.getValueAt(row, 10).toString());
            jTextiid.setText(jTable1.getValueAt(row, 11).toString());
    }//GEN-LAST:event_jTable1MouseClicked

   
     public void updatetable(){
     
         String sql="Select SSN,FName,Minit,LName,City,Street,Six,Salary,jobtype,Hour,FID,IID from Employee";
         try{
             DriverManager.registerDriver(new oracle.jdbc.driver.OracleDriver());
             String url="jdbc:oracle:thin:@localhost:1522:orcl";
             con=DriverManager.getConnection(url,"mob","mob");
             pst=con.prepareStatement(sql);
             rs=pst.executeQuery();
             Object[] columnData=new Object[12];
             
             while(rs.next()){
               columnData[0]=rs.getString("SSN");
               columnData[1]=rs.getString("FName");
               columnData[2]=rs.getString("Minit");
               columnData[3]=rs.getString("LName");
               columnData[4]=rs.getString("City");
               columnData[5]=rs.getString("Street");
               columnData[6]=rs.getString("Six");
               columnData[7]=rs.getFloat("Salary");
               columnData[8]=rs.getString("jobtype");
               columnData[9]=rs.getInt("Hour");
               columnData[10]=rs.getInt("FID");
               columnData[11]=rs.getInt("IID");
               model.addRow(columnData);
             }
             
         }
        catch(Exception e){
         JOptionPane.showMessageDialog(null, e);
        
     }
         
 }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JCheckBox jCheckF;
    private javax.swing.JCheckBox jCheckM;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    public javax.swing.JTextField jTextbid;
    private javax.swing.JTextField jTextcity;
    private javax.swing.JTextField jTexthour;
    private javax.swing.JTextField jTextiid;
    private javax.swing.JTextField jTextjob;
    private javax.swing.JTextField jTextlname;
    private javax.swing.JTextField jTextminit;
    private javax.swing.JTextField jTextname;
    private javax.swing.JTextField jTextsalary;
    private javax.swing.JTextField jTextsearch;
    private javax.swing.JTextField jTextssn;
    private javax.swing.JTextField jTextstreet;
    // End of variables declaration//GEN-END:variables
}
